# Generated by Django 2.0.10 on 2019-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190128_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='hash',
            field=models.TextField(blank=True, null=True, verbose_name='Hash Sala'),
        ),
    ]
