# Generated by Django 2.0.10 on 2019-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sala_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='hash',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sala ID'),
        ),
    ]
