# Generated by Django 2.0.10 on 2019-01-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190128_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nomeSala',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Sala'),
        ),
    ]
