# Generated by Django 2.0.10 on 2019-01-29 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190128_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='userRx',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='userTx',
        ),
        migrations.AddField(
            model_name='sala',
            name='ouvintes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
