# Generated by Django 2.0.10 on 2019-01-29 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20190129_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='ouvintes',
        ),
        migrations.AddField(
            model_name='sala',
            name='userRx',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sala',
            name='userTx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTX', to=settings.AUTH_USER_MODEL),
        ),
    ]
